### ISSUE TITLE
Boris Van Sosin project code 

### ISSUE THREAD

**Issue by Lidkin5** [TechnionYP5777/Internet-Browser-Plugin#16]
Add those links (the code and the user manual)  to the wiki page of the project.

https://www.dropbox.com/s/378e1twha010y2i/user_manual.pdf?dl=0

https://www.dropbox.com/s/ejuenkxzkg5xi6f/yossi_gil-g6a-b9f3514bdf75.zip?dl=0

**Comment by yossigil** [comment]
This is not a concrete issue. How can we know when it is done?

See here:
https://github.com/SpartanRefactoring/Spartanizer/wiki/Issues-etc.

**Comment by Lidkin5** [comment]
The links moved to the wiki page of the project :  
https://github.com/TechnionYP5777/Internet-Browser-Plugin/wiki

**Comment by yossigil** [comment]
What was this issue about?

**Comment by Lidkin5** [comment]
This code may be used in the future for our project. 
so those links are actually references, it's not an issue, as you have indicated ,
so i moved them to the wiki page of the project. 

Is it ok to close this issue? or should i do something else? 
@yossigil

**Comment by yossigil** [comment]
I do not understand what was the task in this issue. Who was assigned, what he did, etc. It looks just like a label to me. Ifyou can make this into a [doable task](https://github.com/SpartanRefactoring/Spartanizer/wiki/Issues-etc.), you can close it after you did.
