### ISSUE TITLE
Welcome, Koby!- add Koby and Sapir to the project. 

### ISSUE THREAD

**Issue by SapirBismot** [TechnionYP5777/Internet-Browser-Plugin#21]
@zvili Can you add @kobybs to the project?
https://github.com/kobybs

**Comment by SapirBismot** [comment]
And add me too ? (now I noticed that I can't assign you)

**Comment by Lidkin5** [comment]
@zvili 
Please add Sapir  ( SapirBismot ) and Koby ( kobybs ) to the project.

**Comment by zvili** [comment]
sapirBismot & Koby added to your project.

**Comment by yossigil** [comment]
@kobybs Hi, can you please add your name [here](https://docs.google.com/document/d/1UvP8tNBX4N-4dRM6ZIFREnbjf9Yvwo3TecFZJmJoApg/edit)
