### ISSUE TITLE
Create an overall design

### ISSUE THREAD

**Issue by nikitadizhur** [TechnionYP5777/Internet-Browser-Plugin#8]
Since the number of packages and classes are starting to grow more and more, there is an approximate representation of how I see the project structure so far. Of course it doesn't claim to be absolute, so any comments and suggestions are welcome. And, moreover, it may be heavily revised if we can find Boris's project.

[Overall design page in wiki](https://github.com/TechnionYP5777/Internet-Browser-Plugin/wiki/Overall-design)

**Comment by Lidkin5** [comment]
About that  multiple views.. 
i think there is no need to separate them, usually you want to separate views , to create complex components and use them in your other views , as one piece. 
Every component in the view will be connected and notified by the relevant entities.

**Comment by yossigil** [comment]
I am not sure this issue makes any sense....

**Comment by nikitadizhur** [comment]
@Lidkin5 I don't really get what you are trying to say... Do you want all GUI be in one giant method/class even if views have no correlation with one another? Soon enough it will get really complex and cumbersome, so no one (besides the one who wrote it) will be able to work with it or change it. And what if you will want to reuse some of the views later? or make many views of the same type or with the same properties?

**Comment by nikitadizhur** [comment]
@yossigil I created this issue to discuss the overall architecture of the project, as we still have some problems with it. If the issue doesn't belong here, then where I should put it?

**Comment by yossigil** [comment]
Maybe define the issue to say: "Create an overall design", and have the deliverable as wiki page?

**Comment by nikitadizhur** [comment]
@yossigil thank you for the advice, I did as you said

**Comment by yossigil** [comment]
So, I guess it is time to close this issue....
